services:
  fms:
    image: ghcr.io/fluid-obx/fms-os-24.04:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    privileged: true

    tty: true
    stdin_open: true

    env_file:
      - ./.env

    tmpfs:
      - /run
      - /run/lock
      - /var/log/journal

    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

      # Data
      - ${COMPOSE_DATA_PATH}:/opt/FileMaker/FileMaker Server
      - ${COMPOSE_OTTO_PATH}:/opt/OttoFMS
      - ${PATH_SHARE}:/share

      # Installer + config
      - ${COMPOSE_CONFIG_PATH}:/config
      - ${COMPOSE_INSTALL_PATH}:/install